name: Auto publish and create release
on:
  push:
    branches: [ master ]
    
jobs:
  autorelease:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --unshallow --tags
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Debug
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx auto label --pr ${{ github.event.number }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm ci
          npx auto create-labels
          npx auto shipit --only-publish-with-release-label
# ggjnn gghgjbb  bb