name: Auto publish and create release
on:
  # push:
  #   branches: [ master ]
    pull_request:
      branches:
        - master
      types:
        - "labeled"
jobs:
  autorelease:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --unshallow --tags
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      

      # - name: Get Pull Request Labels
      #   id: get_labels
      #   run: |
      #     PR_URL=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/pulls" | jq -r '.[0].url')
      #     LABELS=$(curl -s "${PR_URL}/labels" | jq -r '.[].name')
      #     echo "PR Labels: $LABELS"

      - name: run script
        # if: github.event.pull_request.labels[0] != null
        run: echo ${{ github.event.pull_request.labels.*.name[0] }}

      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   if: "!contains(toJson(github.event.pull_request.labels), '[]')"
      #   run: |
      #     npm install
      #     npm ci
      #     npx auto create-labels
      #     npx auto shipit

#ghgh  jjkkk jjjj jjk


