name: Auto publish and create release
on:
  push:
    branches: [ master ]
    
jobs:
  autorelease:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --unshallow --tags
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'


      # - name: get label length
      #   id: getlength
      #   env: 
      #     labels: ${{ toJson(github.event.pull_request.labels) }}
      #   run: |
      #     echo "$labels"
      #     LL=$(echo $labels | jq '. | length' )
      #     echo "::set-output name=Label_Length::$LL"
        
      - name: run script
        # if: github.event.pull_request.labels[0] != null
        run: echo hello


      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   if: "!contains(toJson(github.event.pull_request.labels), '[]')"
      #   run: |
      #     npm install
      #     npm ci
      #     npx auto create-labels
      #     npx auto shipit

#ghgh  jjkkk jjjj


