name: Auto publish and create release
on:
    pull_request:
      branches:
        - master
      types:
        - "labeled"
jobs:
  autorelease:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --unshallow --tags
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
 
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm ci
          npx auto create-labels
          npx auto shipit

#ghgh  jjkkk jjjj jjk ghgh hjhjhj


