# # This is an example pipeline
# name: Release
# on: [push]
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 
#           token: ${{ secrets.GH_TOKEN }} 

#       - name: release
#         uses: mbround18/auto@v1.5.0
#         with:
#           token: ${{ secrets.GH_TOKEN }} 

name: Auto publish and create release
on:
  push:
    branches: [ master ]
jobs:
  autorelease:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --unshallow --tags
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm ci
          npx auto create-labels
          npx auto label --pr ${{ github.event.number }}
          npx auto shipit --only-publish-with-release-label

    #  release major, minor, patch-done 
