# # This is an example pipeline
# name: Release
# on: [push]
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 
#           token: ${{ secrets.GH_TOKEN }} 

#       - name: release
#         uses: mbround18/auto@v1.5.0
#         with:
#           token: ${{ secrets.GH_TOKEN }} 

name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      # - name: Cache node modules
      #   uses: actions/cache@v3
        # with:
        #   path: node_modules
        #   key: yarn-deps-${{ hashFiles('yarn.lock') }}
        #   restore-keys: |
        #     yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Create Release
        env:
         token: ${{ secrets.GH_TOKEN }} 
        run: |
          npm install --frozen-lockfile
          npm build
          npx auto shipit