# # This is an example pipeline
# name: Release
# on: [push]
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 
#           token: ${{ secrets.GH_TOKEN }} 

#       - name: release
#         uses: mbround18/auto@v1.5.0
#         with:
#           token: ${{ secrets.GH_TOKEN }} 

name: Auto publish and create release
on:
  push:
    branches:
      - master
            - next
  pull_request:
    branches:
      - master
jobs:
  autorelease:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --unshallow --tags
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Auto release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npx auto shipit
       
