# # This is an example pipeline
# name: Release
# on: [push]
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 
#           token: ${{ secrets.GH_TOKEN }} 

#       - name: release
#         uses: mbround18/auto@v1.5.0
#         with:
#           token: ${{ secrets.GH_TOKEN }} 

name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags


      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            .npm
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm run build

      - name: Bump Version
        run: npx auto version

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --follow-tags
          npm publish


      # - name: Create Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
      #   run: |
      #     # npm build
      #     npx auto latest
